version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/nhl-api

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run: ls -la node_modules/@nhl-api
      - run: ls -la node_modules/.bin
      - run: yarn test
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}