version: 2.1

jobs:
  test:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverageReporters=text-lcov | coveralls

workflows:
  version: 2
  test:
    jobs:
      - test
