name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10x
        uses: actions/setup-node@master
        with:
          version: 10.x
      - run: |
          npm i -g yarn
          yarn
      # - run: |
      #     yarn test --coverageReporters=text-lcov | coveralls
      #     make test-coverage
      # - name: coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.github_token }}
